package migrations

const (
	createEnum = `
		CREATE TYPE status AS ENUM ('FAIL', 'BEGIN', 'UPLOAD', 'RECOGNITION', 'WAIT', 'DOWNLOAD', 'SUCCESS');
	`

	createTable = `
		CREATE TABLE IF NOT EXISTS voice_recognize_req
		(
			id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			voice_data BYTEA, -- бинарные данные аудио
			process_step status, -- используем созданный enum
			request_file_id VARCHAR, -- ответ от ручки upload
			recognize_id VARCHAR, -- ответ от ручки recognize
			response_file_id VARCHAR, -- ответ от ручки status
			transcription TEXT -- ответ от ручки download (расшифрованный текст)
		);
	`

	dropTable = `
		DROP TABLE IF EXISTS voice_recognize_req;
	`
	dropEnum = `
		DROP TYPE IF EXISTS status;
	`
)
